from __future__ import annotations

import shutil
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
import torch
from ultralytics import YOLO

# ============================================================
# Configuration
# ============================================================

# Directory structure resolution
CURRENT_DIR = Path(__file__).resolve().parent

PROJECT_ROOT = CURRENT_DIR.parent

# Path to the dataset YAML configuration file
DATA_YAML = CURRENT_DIR / "data_detector.yaml"

# Path to the trained YOLO weights checkpoint
MODEL_WEIGHTS = (
    CURRENT_DIR
    / "runs"
    / "detect"
    / "anatomical_region_yolo11m"
    / "weights"
    / "best.pt"
)

# Test images and labels directories generated by prepare_detector_dataset.py
TEST_IMAGES_DIR = PROJECT_ROOT / "detector_dataset" / "images" / "test"
TEST_LABELS_DIR = PROJECT_ROOT / "detector_dataset" / "labels" / "test"

# Output directory for evaluation results and visual inspections
OUTPUT_DIR = CURRENT_DIR / "evaluation_results"
WORST_CROPS_DIR = OUTPUT_DIR / "worst_predictions"

# Image and inference parameters
IMAGE_SIZE = 640  # Consistent with training resolution (or 768)
CONF_THRESHOLD = 0.25  # Minimum confidence to consider a detection
IOU_THRESHOLD = 0.45  # NMS IoU threshold

# Number of worst performing instances to visually extract and save
NUM_WORST_SAMPLES = 20

# Compute target: 0 (for GPU) or "cpu"
DEVICE = 0


# ============================================================
# Geometry and Metric Utilities
# ============================================================


def yolo_to_xyxy(
    x_center: float,
    y_center: float,
    width: float,
    height: float,
    img_w: int,
    img_h: int,
) -> tuple[int, int, int, int]:
    """Convert normalized YOLO format coordinates to absolute pixel bounding box [xmin, ymin, xmax, ymax]."""
    xmin = int((x_center - width / 2.0) * img_w)
    ymin = int((y_center - height / 2.0) * img_h)
    xmax = int((x_center + width / 2.0) * img_w)
    ymax = int((y_center + height / 2.0) * img_h)

    # Clip to valid canvas ranges
    xmin = max(0, min(img_w, xmin))
    ymin = max(0, min(img_h, ymin))
    xmax = max(0, min(img_w, xmax))
    ymax = max(0, min(img_h, ymax))

    return xmin, ymin, xmax, ymax


def calculate_iou(
    box_a: tuple[int, int, int, int], box_b: tuple[int, int, int, int]
) -> float:
    """Calculate Intersection over Union (IoU) between two absolute bounding boxes [xmin, ymin, xmax, ymax]."""
    xa = max(box_a[0], box_b[0])
    ya = max(box_a[1], box_b[1])
    xb = min(box_a[2], box_b[2])
    yb = min(box_a[3], box_b[3])

    inter_area = max(0, xb - xa) * max(0, yb - ya)

    area_a = (box_a[2] - box_a[0]) * (box_a[3] - box_a[1])
    area_b = (box_b[2] - box_b[0]) * (box_b[3] - box_b[1])
    union_area = float(area_a + area_b - inter_area)

    if union_area <= 0:
        return 0.0

    return inter_area / union_area


def read_ground_truth(label_path: Path, img_w: int, img_h: int) -> list[tuple[int, int, int, int]]:
    """Parse normalized YOLO label file and convert to list of absolute [xmin, ymin, xmax, ymax] boxes."""
    if not label_path.exists():
        return []

    boxes = []
    lines = label_path.read_text(encoding="utf-8").strip().splitlines()
    for line in lines:
        parts = line.strip().split()
        if len(parts) >= 5:
            # format: class x_c y_c w h
            _, xc, yc, w, h = map(float, parts[:5])
            boxes.append(yolo_to_xyxy(xc, yc, w, h, img_w, img_h))
    return boxes


# ============================================================
# Visual Inspection & Worst-Case Export
# ============================================================


def inspect_predictions(model: YOLO, device: str) -> None:
    """Run inference over all test images, calculate IoU metrics against ground truth,

    and export visual comparison cards alongside crop regions for the worst-performing samples.
    """
    if not TEST_IMAGES_DIR.exists():
        print(f"Test images directory not found: {TEST_IMAGES_DIR}")
        return

    # Clean and re-create worst crops directory
    if WORST_CROPS_DIR.exists():
        shutil.rmtree(WORST_CROPS_DIR)
    WORST_CROPS_DIR.mkdir(parents=True, exist_ok=True)

    image_extensions = {".jpg", ".jpeg", ".png", ".bmp", ".JPG", ".JPEG", ".PNG"}
    test_image_paths = [p for p in TEST_IMAGES_DIR.iterdir() if p.suffix in image_extensions]

    if not test_image_paths:
        print("No test images found for visual evaluation.")
        return

    print(f"\nRunning visual analysis and IoU scoring across {len(test_image_paths)} test images...")

    inspection_records = []

    for img_path in test_image_paths:
        label_path = TEST_LABELS_DIR / f"{img_path.stem}.txt"

        # Read image
        img_bgr = cv2.imread(str(img_path))
        if img_bgr is None:
            continue
        h, w = img_bgr.shape[:2]

        gt_boxes = read_ground_truth(label_path, w, h)
        gt_box = gt_boxes[0] if gt_boxes else None

        # Predict with YOLO
        results = model.predict(
            source=img_bgr,
            imgsz=IMAGE_SIZE,
            conf=CONF_THRESHOLD,
            iou=IOU_THRESHOLD,
            device=device,
            verbose=False,
        )

        boxes_obj = results[0].boxes
        pred_box = None
        conf = 0.0

        if len(boxes_obj) > 0:
            # Select top-confidence prediction
            best_idx = int(torch.argmax(boxes_obj.conf).item())
            coords = boxes_obj.xyxy[best_idx].cpu().numpy().astype(int)
            pred_box = (coords[0], coords[1], coords[2], coords[3])
            conf = float(boxes_obj.conf[best_idx].item())

        # Calculate IoU score against Ground Truth
        if gt_box is not None and pred_box is not None:
            iou = calculate_iou(gt_box, pred_box)
            status = "Detected"
        elif gt_box is not None and pred_box is None:
            iou = 0.0
            status = "False Negative (Missed)"
        else:
            iou = 0.0
            status = "No Ground Truth"

        inspection_records.append(
            {
                "image_name": img_path.name,
                "image_path": str(img_path),
                "iou": iou,
                "confidence": conf,
                "status": status,
                "gt_box": gt_box,
                "pred_box": pred_box,
            }
        )

    # Convert to DataFrame and sort by worst IoU / Confidence
    df_results = pd.DataFrame(inspection_records)
    df_results.sort_values(by=["iou", "confidence"], ascending=[True, True], inplace=True)

    # Save summary report CSV
    csv_report_path = OUTPUT_DIR / "test_set_iou_report.csv"
    df_results.to_csv(csv_report_path, index=False)
    print(f"Complete IoU evaluation CSV saved to: {csv_report_path}")

    # Extract worst N samples for visual inspection
    worst_samples = df_results.head(NUM_WORST_SAMPLES)
    print(f"Exporting top {len(worst_samples)} worst detections for visual inspection to: {WORST_CROPS_DIR}")

    for rank, (_, row) in enumerate(worst_samples.iterrows(), start=1):
        img_bgr = cv2.imread(row["image_path"])
        canvas = img_bgr.copy()
        gt_box = row["gt_box"]
        pred_box = row["pred_box"]
        iou_val = row["iou"]
        conf_val = row["confidence"]

        # Draw Ground Truth bounding box in GREEN
        if gt_box is not None:
            cv2.rectangle(
                canvas,
                (gt_box[0], gt_box[1]),
                (gt_box[2], gt_box[3]),
                (0, 255, 0),
                2,
            )
            cv2.putText(
                canvas,
                "Ground Truth",
                (gt_box[0], max(20, gt_box[1] - 8)),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.55,
                (0, 255, 0),
                2,
            )

        # Draw Prediction bounding box in RED (or BLUE if IoU > 0.5)
        if pred_box is not None:
            color = (0, 0, 255) if iou_val < 0.5 else (255, 120, 0)
            cv2.rectangle(
                canvas,
                (pred_box[0], pred_box[1]),
                (pred_box[2], pred_box[3]),
                color,
                2,
            )
            cv2.putText(
                canvas,
                f"Pred (Conf: {conf_val:.2f}, IoU: {iou_val:.2f})",
                (pred_box[0], max(20, pred_box[1] - 8)),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.55,
                color,
                2,
            )

            # Crop the predicted anatomical region to inspect what BCS model will see
            crop_img = img_bgr[pred_box[1] : pred_box[3], pred_box[0] : pred_box[2]]
            if crop_img.size > 0:
                crop_name = f"rank{rank:02d}_crop_iou_{iou_val:.2f}_{Path(row['image_name']).stem}.jpg"
                cv2.imwrite(str(WORST_CROPS_DIR / crop_name), crop_img)

        # Save annotated full comparison image
        annotated_name = f"rank{rank:02d}_full_iou_{iou_val:.2f}_{Path(row['image_name']).stem}.jpg"
        cv2.imwrite(str(WORST_CROPS_DIR / annotated_name), canvas)


# ============================================================
# Main Evaluation Pipeline
# ============================================================


def main() -> None:
    """Run standard Ultralytics mAP validation and perform visual inspection."""
    if not DATA_YAML.exists():
        raise FileNotFoundError(f"Missing dataset config: {DATA_YAML}")

    if not MODEL_WEIGHTS.exists():
        raise FileNotFoundError(
            f"Weights not found at {MODEL_WEIGHTS}. Ensure training has completed."
        )

    # Set compute device
    if DEVICE != "cpu" and not torch.cuda.is_available():
        device = "cpu"
    else:
        device = DEVICE

    print(f"Loading trained weights from: {MODEL_WEIGHTS}")
    model = YOLO(str(MODEL_WEIGHTS))

    print("\n" + "=" * 55)
    print("STEP 1: Standard Validation on Test Split")
    print("=" * 55)

    # Run standard validation to generate metrics
    metrics = model.val(
        data=str(DATA_YAML),
        split="test",
        imgsz=IMAGE_SIZE,
        device=device,
        verbose=True,
    )

    print("\n================== Test Set Metrics ==================")
    print(f"mAP@50:        {metrics.box.map50:.4f}")
    print(f"mAP@50-95:     {metrics.box.map:.4f}")
    print(f"Mean Precision:{metrics.box.mp:.4f}")
    print(f"Mean Recall:   {metrics.box.mr:.4f}")
    print("======================================================")

    print("\n" + "=" * 55)
    print("STEP 2: Detailed Visual Inspection & Worst-Crop Extraction")
    print("=" * 55)
    inspect_predictions(model=model, device=device)

    print("\nEvaluation successfully completed.")
    print(f"Results and worst crop visuals stored at:\n{OUTPUT_DIR.resolve()}")


if __name__ == "__main__":
    main()
